Repository McBaxck/cmdb, pull requests merged in 2022-10, with the labels that each got.

#16 Database dev
  Database/Database.py
  Database/Db_serveur
  Database/Db_serveur.db
  Database/script_sql.sql
Labels: à faire

#22 Class develop vers Develop
  classes/__pycache__/database.cpython-39.pyc
  classes/__pycache__/dd.cpython-39.pyc
  classes/__pycache__/interface_database.cpython-39.pyc
  classes/__pycache__/partition.cpython-39.pyc
  classes/__pycache__/server.cpython-39.pyc
  classes/database/__init__.py
  classes/database/__pycache__/test_hello.cpython-39-pytest-7.1.3.pyc
  classes/database/database.py
  classes/database/duplicates/interface_reseau_database.py
  classes/database/duplicates/interface_reseau_route_database.py
  classes/database/interfaces/interface_database.py
  classes/database/interfaces/interface_reseau.py
  classes/database/interfaces/interface_reseau_database.py
  classes/database/interfaces/interface_reseau_route_database.py
  classes/database/interfaces/ip_table_rules_database.py
  classes/database/securite_database.py
  classes/database/server/server_database.py
  classes/database/service_factory.py
  classes/database/stockage/hard_disk_database.py
  classes/database/stockage/partition_database.py
  classes/server/config/interface_reseau.py
  classes/server/config/interface_reseau_route.py
  classes/server/config/ip_table_rules.py
  classes/server/config/policy.py
  classes/server/config/route.py
  classes/server/config/securite.py
  classes/server/server.py
  classes/server/stockage/dd.py
  classes/server/stockage/partition.py
  classes/server/stockage/raid.py
  classes/server/types/phy.py
  classes/server/types/vm.py
  server/srv.py
Labels: feature, en développement

#26 ajout de commentaires
  classes/database/interfaces/interface_database.py
  classes/database/service_factory.py
  classes/server/config/ip_table_rules.py
  classes/server/config/policy.py
  classes/server/server.py
  classes/server/stockage/raid.py
  classes/server/types/phy.py
  classes/server/types/vm.py
Labels: réalisé

#31 Test unitaire leo + commentaires création bdd
  Database.py
  __pycache__/tests.cpython-39-pytest-6.2.4.pyc
  classes/__pycache__/__init__.cpython-39.pyc
  classes/server/__pycache__/server.cpython-39.pyc
  classes/server/config/__pycache__/interface_reseau.cpython-39.pyc
  classes/server/config/__pycache__/interface_reseau_route.cpython-39.pyc
  classes/server/config/__pycache__/ip_table_rules.cpython-39.pyc
  classes/server/config/__pycache__/policy.cpython-39.pyc
  classes/server/config/__pycache__/securite.cpython-39.pyc
  classes/server/server.py
  classes/server/stockage/__pycache__/dd.cpython-39.pyc
  classes/server/stockage/__pycache__/partition.cpython-39.pyc
  classes/server/stockage/__pycache__/raid.cpython-39.pyc
  classes/server/stockage/partition.py
  tests.py
Labels: réalisé
